### ISSUE TITLE
yesno and ask = FALSE

### ISSUE THREAD

**Issue by joethorley** [bcgov/rems#10]
Hi @ateucher 

Two thoughts for download_historic_data (which works again thanks)

1) I have a small package yesno <https://github.com/poissonconsulting/yesno> that asks the question in the style of devtools (I will be pushing to CRAN once I hear back from Hadley Wickham about co-authorship). 

2) would it be possible to add the argument ask = FALSE (which means that if the user does nothing it asks but if the user consciously chooses to override i.e. ask = TRUE it does it automatically - I like it for allowing scripts to run without human intervention)

both just suggestions - feel free to ignore and close this issue

Joe

**Comment by ateucher** [comment]
I saw your yesno package - looks handy. I may use it once it hits CRAN!

As for the `ask = FALSE`, good idea. I added the question to comply with CRAN policy (see #4), but presumably allowing an override would still be okay.

**Comment by joethorley** [comment]
I'll let you know when its on CRAN.

I have reached the conclusion that an override is okay to comply with the policy. Otherwise the functions use in a script is really problematic.

**Comment by ateucher** [comment]
That should do it I think... reopen if it doesn't work for you!
