### ISSUE TITLE
Check for and possibly clean duplicate rows

### ISSUE THREAD

**Issue by ateucher** [bcgov/rems#18]

**Comment by HeatherGranger** [comment]
@ateucher EMS data will usually have 1) 2 rows with same date/time. The microbiological data usually occupies a second row for some reason. These rows could maybe be combined with some type of check that data is being overwritten....
2) Empty rows with only one column filled in (date, depth, EMS ID) but with no data.

**Comment by ateucher** [comment]
Thanks @HeatherGranger - Are you seeing these in the 2yr dataset?

I have found some where there seems to be a replicate sample. Some of these are denoted as such in the `SAMPLE_CLASS` column, which I propose we add to the default set of wq columns. There are others that appear to be replicates (same date, EMS ID, parameter) but with different values.

**Comment by ateucher** [comment]
There are also some duplicated date/emsid/parameters with different `ANALYTICAL_METHOD`s and/or `PERMIT`.

**Comment by HeatherGranger** [comment]
@ateucher I haven't worked with the 2 yr dataset closely enough to know. There doesn't appear to be any blank RESULT fields though. I agree, adding SAMPLE_CLASS  as a default would help with cleaning. Same date/emsid/parameter but differing in permit and/or analytical method should be considered different measurements. Having the SAMPLE_CLASS would help determine that.

**Comment by ateucher** [comment]
Great, thanks @HeatherGranger. Since this doesn't seem to a problem with `rems`, I'll close the issue, but happy to help with strategies offline.
