### ISSUE TITLE
option to not ask to download most recent data

### ISSUE THREAD

**Issue by joethorley** [bcgov/rems#21]
More a suggestion than an issue.

Having played around with a wrapper on the rems functions to get data my only suggestion is to add an option to allow the user to not be asked if they want to download the most recent data. ie sort of the opposite of force. That is to says rems makes no attempt to get new data (it could issue a message or warning but should not require user intervention to proceed).

**Comment by HeatherGranger** [comment]
What would be the benefit of this? Maybe if you're just worried about a certain time period I guess and don't care about recent data...
I always want the most recent set of data when I run rems and always say yes to download.

**Comment by ateucher** [comment]
I think I can see the rationale - so if you're running it in a script it doesn't require user intervention. @HeatherGranger I would make the argument something like `check_updates`  with a default value of `TRUE` so that the behaviour doesn't change from current.
