### ISSUE TITLE
Check compatibility with upcoming dplyr release

### ISSUE THREAD

**Issue by ateucher** [bcgov/rems#22]
https://blog.rstudio.org/2017/04/13/dplyr-0-6-0-coming-soon/

**Comment by ateucher** [comment]
Looks okay right now, but at some point will need to port over code: http://dplyr.tidyverse.org/articles/programming.html

**Comment by ateucher** [comment]
dplyr 0.7 has hit the streets with big changes to dealing with non-standard evaluation - a new system called tidyeval. See `vignette("programming")`.

This isn't urgent yet, as the underscored versions of the dplyr verbs are deprecated, but not defunct (yet).

Will also need to look at the sqlite backend stuff as that has changed as well with dbplyr.

**Comment by stephhazlitt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Enhancements](https://trello.com/c/vGokuUfX/9-enhancements)

**Comment by ateucher** [comment]
Need to bump dplyr version to 0.7 and add dbplyr in Imports.

**Comment by ateucher** [comment]
Some good resources here: http://maraaverick.rbind.io/2017/08/tidyeval-resource-roundup/

**Comment by ateucher** [comment]
It's been four years and this has been fixed incrementally over time.
