### ISSUE TITLE
Add package-level documentation

### ISSUE THREAD

**Issue by stephhazlitt** [bcgov/rems#27]
It would be useful of users could get the list of functions using `?rems` in the console.

**Comment by boshek** [comment]
I could be wrong, but I think the convention is that `?package-name` provide an overview of the package and then `help(package = "rems")` provides a list of functions.

**Comment by stephhazlitt** [comment]
I am sure you are correct. At this time `?rems` brings up nothing -- and many users use this path to get to the list of functions via the index. I am not sure what the overview documentation is called, but I think it would be useful to add to `rems`.

**Comment by ateucher** [comment]
yeah, I almost never use `help(package = "rems")` - can never remember the syntax. `?rems` is much nicer

**Comment by ateucher** [comment]
and behold `usethis::use_package_doc()`
