### ISSUE TITLE
MDL_UNIT column addition to raw data

### ISSUE THREAD

**Issue by HeatherGranger** [bcgov/rems#30]
DataBC test objects were just reviewed for the addition of an MDL_UNIT column. Once put into production, `get_ems_data` wq default cols should include MDL_UNIT column. This will clear up any confusion between if the RESULT is a different unit than the MINIMUM_DETECTION_LIMIT. 

This issue started with this closed issue in `wqbc`. 
https://github.com/bcgov/wqbc/issues/68

**Comment by ateucher** [comment]
Closed in  7437212
