### ISSUE TITLE
Download data for only one site at a time/ more download flexibility

### ISSUE THREAD

**Issue by giligone** [bcgov/rems#33]
I love the idea of being able to pull EMS data directly into R but I would like to have more flexibility the download process. Namely it'd be great to have the option to set in R what I want to download as opposed to having to pre-fetch the entire EMS and then working with in R. I know this would result in many more db calls to the EMS system but I think it would really open up the options for what you could build.

**Comment by HeatherGranger** [comment]
Using `filter_ems_data` you can pare down the dataset to just one or a subset of sites. Check out the readme. I've also used the filter function to further refine the dataset. You can also specify a subset of columns to download (?filter_ems_data in the R console will tell you the options to do that I believe). I've used rems for the `water-quality-analysis-northeastbc` repo, check that out if you want some examples.

**Comment by giligone** [comment]
Thanks for the quick reply! :) 
I did test those functions but unless I'm missing something, the first step will pre-fetch the entire EMS either as 2 yr/ 4 yr/ or historical and then cache that locally before you can do any filtering. My thought would be to specify in step one that I am only interested in site X and then that would pull only the data for site X from the EMS. Instead of having 1 500mb download you'd have many 10 kb downloads. If that makes sense.

**Comment by ateucher** [comment]
Hi @giligone. I'm afraid this is not possible as `rems` is not actually reading from the EMS database, but rather using the very large `.csv` files exported from EMS: https://catalogue.data.gov.bc.ca/dataset/bc-environmental-monitoring-system-results. So the only way to access it is to download the file in its entirety and then use `filter_ems_data` as @HeatherGranger mentioned.
