### ISSUE TITLE
Specify path for sqlite database

### ISSUE THREAD

**Issue by sinclairjesse** [bcgov/rems#58]
rems uses Appdata/Local for storing the sqlite database. Could an argument be added for users to specify where to store that database? Consequently,  a *read from path* argument would likely need to be added to the read functions unless the user-specified path could get stored.

**Comment by ateucher** [comment]
Hi @sinclairjesse - this is actually already possible. You can specify/customize the location of the sqlite database via an
option `rems.historic.path`. This is best set in your `.Rprofile` file as
`options(rems.historic.path = "path_to_file")`.

This is not widely used as far as I know, so if you test it and find any issues please report it here!

**Comment by ateucher** [comment]
Correction - I think that option should point to a directory path, not a file - the sqlite file will be created in and accessed from that directory.

**Comment by sinclairjesse** [comment]
Thanks @ateucher! I didn't catch that in the documentation. Is there a similar argument for the 2 or 4 yr datasets? Or does specifying that option cover all of the databases?

**Comment by ateucher** [comment]
Currently it just sets the location for the historic SQLite database

**Comment by ateucher** [comment]
I suppose it makes sense for that to be a global option (and it should be better documented). What is your use case for setting the location manually?

**Comment by sinclairjesse** [comment]
I am looking to store a copy externally (e.g., server). Mainly because of space limitations on my laptop, but would also like to access  from multiple computers without having to download and store a version on each.

**Comment by ateucher** [comment]
Ok so just having the historic file location specified by this works for you?

**Comment by sinclairjesse** [comment]
Yup. It works for me. Thanks @ateucher
