### ISSUE TITLE
Repair rems cache without attaching rems

### ISSUE THREAD

**Issue by steffilazerte** [bcgov/rems#61]
I think some of the issues I've been running into are because I've been trying to use specific rems functions via rems::function() rather than explicitly attaching the package with library(rems). This results in my cache being occasionally removed, but not being setup again (which happens during .onLoad). 

Is this just the way it is? Or, could there be a check for fixing semi-removed caches when checking for updates? I'm admittedly not 100% sure how the caching works, however, so this maybe a weird ask!

**Comment by ateucher** [comment]
I think I'm going to leave this one to see if #63 takes care of it. Can you ping me back here if it doesn't?

**Comment by ateucher** [comment]
Closing this now. Please reopen if it happens again!
