### ISSUE TITLE
`download_historic_data()` fails with duckdb version 0.8.0

### ISSUE THREAD

**Issue by KarHarker** [bcgov/rems#76]
Error message below:

```
Error: rapi_execute: Failed to run query
Error: Invalid Input Error: CSV File not supported for multithreading. This can be a problematic line in your CSV File or that this CSV can't be read in Parallel. Please, inspect if the line 367668 is correct. If so, please run single-threaded CSV Reading by setting parallel=false in the read_csv call.
```

**Comment by ateucher** [comment]
Perhaps related? https://github.com/duckdb/duckdb/issues/7702

**Comment by evgenimatveev** [comment]
Hi Andy, I have the exact same problem and I'm just wondering if there are any solutions? Thanks!

**Comment by evgenimatveev** [comment]
@KarHarker, don't suppose you found a solution to this did you?

**Comment by ateucher** [comment]
I'm looking at this again now...

**Comment by evgenimatveev** [comment]
@ateucher thanks a bunch. Tbh, after looking into it more there's a good chance the issue is on my end. I'm using a different comp and it seems like it doesn't have enough RAM. I asked a colleague to try on a desktop and that worked. Interesting that this is the error it gives.

**Comment by ateucher** [comment]
That's good to know, thanks! However I'd like it to be robust enough to work on really any machine. Can you please try this now?

```r
devtools::install_github("bcgov/rems", ref = "fix-read-duckdb")
rems:::burn_it_down()
# restart RStudio
library(rems)
download_historic_data()
```

**Comment by evgenimatveev** [comment]
@ateucher brilliant, thanks so much! Worked like a charm.

**Comment by ateucher** [comment]
Thanks @evgenimatveev - that's super helpful! There is a strange timezone bug happening now that I need to look into...

**Comment by KarHarker** [comment]
@ateucher - you're a legend. Thanks for this fix!
